name: Terraform Destroy
on:
  workflow_dispatch:  

jobs:
  terraform-destroy:
    name: Terraform destroy
    runs-on: ubuntu-latest
      
    defaults:
      run:
        shell: bash
        
    steps:      
    - name: Obtendo o código
      uses: actions/checkout@v3

    - name: Setup terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 

     #- name: Azure CLI script
     #   uses: azure/cli@v2
     #   with:
     #     azcliversion: latest
     #     inlineScript: |
     #       az account show

    - name: Terraform Init
      run: terraform init

    - name: Terraform Destroy
      run: terraform destroy -var-file dev.tfvars
