name: 'Terraform Deployment'
on:
  push:
    branches: ["main"]
  workflow_dispatch:  
jobs:
  Terraform:
  name: 'Terraform'
  runs-on: ubuntu-latest
  environment: production
  defaults:
      run:
        shell: bash
  steps:      
     - name: Obtendo o código
       uses: actions/checkout@v4.1.5

     - name: 'Setup terraform'
       uses: hashicorp/setup-terraform@v3
       with:
         terraform_version: "1.1.7"

     - name: Azure Login
       uses: azure/login@v2
       with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}    

     
    
  
  
